clear vars;
close all;

addpath('figs');
addpath('core');
addpath('lib');



o = ImageCompositor();

o.camera = Camera('2','Li6');

o.figures = {...
        FilePickerFigure...
        IntegratedODxFigure...
        IntegratedODCroppedxFigure...
        InformationFigure...
        IntegratedODyFigure...       
        ImageFigure...        
        CroppedImageFigure... 
        IntegratedODCroppedyFigure...        
        ReferenceImageFigure...
        AtomsImageFigure...
        ProtocolFigure...
        FitControlFigure...
        AnalysisFigure...
        ...NondefringedFigure...
        ...DefringedFigure...
        ...ImagePackageFigure...      
        ...CutODFigure...        
        ...IODDefyFigure...
        ...IODDefxFigure...
        HistoryFigure...
        ...WidthFigure..  
    };


o.create();
