clearvars
close all;


% addpath '/afs/physnet.uni-hamburg.de/project/bfm/Benutzer/Matthias/Code/2016-05-09 MatlabLib'
% addpath '/afs/physnet.uni-hamburg.de/project/bfm/Benutzer/Matthias/Code/2016-05-09 MatlabLib/GUI'
addpath '//afs/physnet.uni-hamburg.de/project/bfm/Benutzer/Matthias/Code/2016-05-09 MatlabLib'
addpath '//afs/physnet.uni-hamburg.de/project/bfm/Benutzer/Matthias/Code/2016-05-09 MatlabLib/GUI'
addpath('figs');
addpath('core');
addpath('lib');
%addpath('../../');



o = ImageCompositor();
o.figures = {...
        FilePickerFigure...
        IntegratedODxFigure...
        IntegratedODCroppedxFigure...
        InformationFigure...
        IntegratedODyFigure...       
        ImageFigure...        
        CroppedImageFigure... 
        IntegratedODCroppedyFigure...        
        AbsorptionImageFigure...
        ReferenceImageFigure...
        HistoryFigure...      
        CutODFigure...        
        OscillationFigure... 
        ProtocolFigure...
    };

%o.userIndeces.time = UserIndex(1,1,numel(o.data.times));
% o.userIndices.frequency = UserIndex(3,1,200);
% o.userIndices.run = UserIndex(0,0,250);
% o.userIndices.imbalance = UserIndex(1,1,15);
% o.userIndices.imbalance2 = UserIndex(1,1,15);

o.camera = Camera('3','K');
%o.camera{2} = Camera('PCO');


o.create();

%% fit all